use libs::api::app_error::Error;

#[tokio::main]
async fn main() -> Result<(), Error>{
    
    Ok(())
}
